version: '3'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_optimisation
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./serveur
      dockerfile: Dockerfile
    container_name: api_optimisation
    ports:
      - "3001:3001"
    volumes:
      - ./serveur:/app
      - /app/node_modules
      - .:/project
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/optimisation
      - NODE_ENV=development
    depends_on:
      - mongodb

  k6:
    image: grafana/k6:latest
    container_name: k6_benchmark
    volumes:
      - ./load-tests:/scripts:ro # Montage en lecture seule
    environment:
      - API_URL=http://api:3001/api
    entrypoint: ["echo", "k6-ready"]

volumes:
  mongo_data:
